/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_lpuart.h"
#include "fsl_clock.h"
#include "ff.h"
#include "diskio.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define BOARD_LPUART1_PERIPHERAL LPUART1
/* Definition of the clock source frequency */
#define BOARD_LPUART1_CLOCK_SOURCE 80000000UL
/* Rx transfer buffer size. */
#define BOARD_LPUART1_RX_BUFFER_SIZE 10
/* Rx transfer buffer size. */
#define BOARD_LPUART1_TX_BUFFER_SIZE 10
/* LPUART1 interrupt vector ID (number). */
#define BOARD_LPUART1_IRQN LPUART1_IRQn

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const lpuart_config_t BOARD_LPUART1_config;
extern lpuart_handle_t BOARD_LPUART1_handle;
extern uint8_t BOARD_LPUART1_rxBuffer[BOARD_LPUART1_RX_BUFFER_SIZE];
extern lpuart_transfer_t BOARD_LPUART1_rxTransfer;
extern uint8_t BOARD_LPUART1_txBuffer[BOARD_LPUART1_TX_BUFFER_SIZE];
extern lpuart_transfer_t BOARD_LPUART1_txTransfer;
/* FATFS System object */
extern FATFS FATFS_System_0;
/* FATFS File object */
extern FIL FATFS_File_0;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
